### ISSUE TITLE
GUI items are removed when moved

### ISSUE THREAD

**Issue by Khikki** [Matt-MX/ServerGUI#2]
GUI items are removed when moved
https://youtu.be/x2b0LWsg8TQ
*I clarify that this is just a visual bug, but still.

**Comment by Khikki** [comment]
Also, when connecting to the server, the message (connection: "&7 Attempting to connect you to &f%server%") is duplicated twice.

**Comment by CoolDCB** [comment]
After seeing this bug I've deleted the plugin as this is quite a large issue really.

**Comment by Matt-MX** [comment]
I think this has been fixed, it may have been a protocolize issue, if not already fixed; it will be.
