### ISSUE TITLE
Feature Request: Compatibility with running other velocity commands

### ISSUE THREAD

**Issue by CoolDCB** [Matt-MX/ServerGUI#3]
It would be amazing to have support for other commands to be ran from other plugins on Velocity. For example, we use a AJQueues for our server and don't want players to direct connect which the GUI allows. It would be awesome if we could connect it to our queue plugin.

**Comment by Matt-MX** [comment]
This would be possible but I don't personally see the point.
I think I'll add a small API for people to use with their own plugins, so if you want to do that then it will be an option.
